//====================================================================================----
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//====================================================================================----

namespace NOSBlog.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.user_item_collections = new HashSet<user_item_collections>();
        }
    
        public int id { get; set; }
        // ==========================================
        [DisplayName("Item's Name")]
        [Required(ErrorMessage = "Item's name is require")]
        [MaxLength(255, ErrorMessage = "Max length is 255")]
        public string name { get; set; }
        // ==========================================
        [DisplayName("Image")]
        public string image { get; set; }
        // ==========================================
        [DisplayName("Price")]
        [Required(ErrorMessage = "Price is require")]
        [Range(0, 99999, ErrorMessage = "Price range from 0 to 99999")]
        public int price { get; set; }
        // ==========================================
        [DisplayName("Reduce price")]
        [Required(ErrorMessage = "Reduce price is require")]
        public int reduce { get; set; }
        // ==========================================
        [DisplayName("Quantity")]
        [Required(ErrorMessage = "Quantity is require")]
        [Range(0, 999, ErrorMessage = "Quantity range from 0 to 999")]
        public int quantity { get; set; }
        // ==========================================
        [DisplayName("Type")]
        [Required(ErrorMessage = "Type is require")]
        [Range(1, 20, ErrorMessage = "Type range from 0 to 20")]
        public byte type { get; set; }
        // ==========================================
        [DisplayName("Collectoin points")]
        [Required(ErrorMessage = "Collection points is require")]
        [Range(0, 999999, ErrorMessage = "Collection points range from 0 to 999999")]
        public int collection_points { get; set; }
        // ==========================================
        public bool @lock { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }

        // Image file
        public HttpPostedFileBase imageFile;
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_item_collections> user_item_collections { get; set; }
    }
}
