//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSBlog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NOSBlogEntities : DbContext
    {
        public NOSBlogEntities()
            : base("name=NOSBlogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<blog> blogs { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<image> images { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_like_blogs> user_like_blogs { get; set; }
        public virtual DbSet<user_like_comments> user_like_comments { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<user_item_collections> user_item_collections { get; set; }
    }
}
