//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_item_collections
    {
        public Nullable<int> user_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public int collection_points { get; set; }
        public int price { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual item item { get; set; }
        public virtual user user { get; set; }
    }
}
