//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOSBlog.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.blogs = new HashSet<blog>();
            this.comments = new HashSet<comment>();
            this.user_like_blogs = new HashSet<user_like_blogs>();
            this.user_like_comments = new HashSet<user_like_comments>();
            this.user_item_collections = new HashSet<user_item_collections>();
        }
    
        public int id { get; set; }
        [DisplayName("First name"), Required(ErrorMessage = "Fisrt name is required")]
        [StringLength(50, ErrorMessage = "{0} length must be between {2} and {1}.", MinimumLength = 1)]
        public string first_name { get; set; }
        [DisplayName("Last name"), Required(ErrorMessage = "Last name is required")]
        [StringLength(50, ErrorMessage = "{0} length must be between {2} and {1}.", MinimumLength = 1)]
        public string last_name { get; set; }
        [DisplayName("Username"), Required(ErrorMessage = "Username is required")]
        [RegularExpression("[a-z_0-9]{5,16}", ErrorMessage = "Username only accept a-z and 0-9, length from 5 to 15")]
        public string username { get; set; }
        [DisplayName("Email"), Required(ErrorMessage = "Email is required")]
        [RegularExpression("^([\\w\\.\\-]+)@([\\w\\-]+)((\\.(\\w){2,3})+)$", ErrorMessage = "Email format is incorret")]
        public string email { get; set; }
        [DisplayName("Phone"), Required(ErrorMessage = "Phone is required")]
        [RegularExpression("[0-9]{10}", ErrorMessage = "Phone must have 10 numbers")]
        public string phone { get; set; }
        [DisplayName("Password"), Required(ErrorMessage = "Password is required")]
        [StringLength(255, ErrorMessage = "{0} length must be between {2} and {1}.", MinimumLength = 6)]
        public string password { get; set; }
        public int role { get; set; }
        public string avatar { get; set; }
        public bool blue_tick { get; set; }
        public int coins { get; set; }
        public int collection_points { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blog> blogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_like_blogs> user_like_blogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_like_comments> user_like_comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_item_collections> user_item_collections { get; set; }
    }
}
